server:
  port: ${PORT:8080}
spring:
  application:
    name: spring_boot_querydsl_example
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5433/spring_boot_querydsl_example
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        #implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        use_sql_comments: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  jackson:
    serialization:
      indent-output: true
      fail-on-empty-beans: false
  liquibase:
    change-log: classpath:db/changelog-master.yaml